### ISSUE TITLE
City Composite Implementation and District Division Check

### ISSUE THREAD

**Issue by Crispykitty** [COS214-Project-2024/Team-12#1]
Implement the City Composite structure and conduct testing to confirm functionality in adding buildings to the city. Additionally, we will evaluate the feasibility of dividing the city into districts to determine if this approach aligns with our project goals. 

Task Breakdown:

1. Code the City Composite structure.
2. Test functionality by adding buildings to the city and ensuring successful integration within the City Composite.
3. Check if dividing the city into districts is feasible for our project requirements.

Deadline:
(2024/10/26)

Acceptance Criteria:

- [x] City Composite implemented successfully.
- [x] Building addition confirmed within the City Composite structure.
- [x] Decision made on whether to maintain or discard district division in the city.

**Comment by Sibusiso-Z** [comment]
By my troth, it will be done.
